title: 6reg's portfolio
author: 6reg
email: mathiasgreg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 My coding projects, demonstating my skills with React and Firebase. 

# social links
twitter_username: 6reg
github_username:  6reg

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
